# DivineSense golangci-lint Configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

# ===========================================================================
# Run Configuration
# ===========================================================================
run:
  go: "1.25"
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  concurrency: 4

# ===========================================================================
# Linters Configuration
# ===========================================================================
linters:
  default: none
  enable:
    # Static analysis (enabled by default)
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign

    # Additional linters
    - errorlint
    - prealloc
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - gocritic
    - misspell
    - unconvert
    - nilerr
    - gosec

  # Linter-specific settings (v2 format: under linters.settings)
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    errcheck:
      check-type-assertions: true
      check-blank: true

    gosec:
      excludes:
        - G104
        - G307
        - G301
        - G204
        - G115
        - G107
        - G304
        - G306
        - G109
        - G201
        - G202

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - unnamedResult
        - ifElseChain
        - commentedOutCode
        - unnecessaryDefer
        - appendCombine
        - paramTypeCombine
        - importShadow
        - octalLiteral
        - builtinShadow
        - emptyStringTest

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    misspell:
      locale: US

  # Exclusion rules (v2 format: under linters.exclusions)
  exclusions:
    # Exclude generated files
    generated: lax

    # Exclude paths
    paths:
      - build
      - dist
      - vendor
      - third_party
      - testdata
      - examples
      - Godeps
      - builtin
      - proto/gen
      - server/router/frontend
      - ".*\\.gen\\.go$"
      - ".*\\.mock\\.go$"
      - ".*_string\\.go$"

    # Exclusion rules
    rules:
      # Test files: relax error checking
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - bodyclose
          - sqlclosecheck
          - nilerr
          - prealloc
          - unconvert
          - unused

      # Main packages
      - path: cmd/
        linters:
          - unused

      # Plugin code
      - path: plugin/
        linters:
          - staticcheck
        text: "ST1005"

      # Mock files
      - path: '\.mock\.go$'
        linters:
          - gocritic
          - misspell
          - errcheck
          - prealloc

      # AI agent callbacks - relax error checking
      - path: plugin/ai/
        linters:
          - errcheck
          - errorlint
          - nilerr
          - gosec
          - unconvert
          - prealloc

      # Plugin code - common exclusions
      - path: plugin/
        linters:
          - errcheck
          - gosec
          - prealloc
          - staticcheck
          - gocritic
          - ineffassign

      # Server code - common exclusions
      - path: server/
        linters:
          - errcheck
          - gosec
          - unconvert
          - gocritic
          - prealloc
          - ineffassign
          - nilerr
          - errorlint

      # Store code
      - path: store/
        linters:
          - errcheck
          - gosec
          - prealloc
          - gocritic
          - staticcheck

      # Internal code
      - path: internal/
        linters:
          - gosec

      # Common patterns to exclude everywhere
      - path: '(.+)\.go$'
        linters:
          - gocritic
        text: "hugeParam:"

      - path: '(.+)\.go$'
        linters:
          - gocritic
        text: "rangeValCopy:"

      - path: '(.+)\.go$'
        linters:
          - gocritic
        text: "unnamedResult:"

      - path: '(.+)\.go$'
        linters:
          - staticcheck
        text: "SA1019:"

      - path: '(.+)\.go$'
        linters:
          - staticcheck
        text: "SA4006:"

      - path: '(.+)\.go$'
        linters:
          - misspell
        text: "`cancelled`"

      - path: '(.+)\.go$'
        linters:
          - misspell
        text: "`dialogues`"

# ===========================================================================
# Formatters Configuration (v2 separates formatters)
# ===========================================================================
formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - build
      - dist
      - vendor
      - proto/gen

# ===========================================================================
# Output Configuration
# ===========================================================================
output:
  formats:
    text:
      path: stdout
      colors: true
  sort-order:
    - linter
    - file
