version: 2

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocritic
    - printf
    - nilerr
    - errorlint
    - prealloc
    - unconvert
    - unparam
    - revive
    - misspell
    - sqlclosecheck
    - rowserrcheck
    - godot
    - forbidigo
    - mirror
    - bodyclose
  disable:
    - exhaustive
    - exhaustivestruct
    - funlen
    - lll
    - gocyclo

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    excludes:
      - G104

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  revive:
    enable-all-rules: true
    rules:
      - name: file-header
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: confusing-results
        disabled: true
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: nested-structs
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: early-return
        disabled: true
      - name: use-any
        disabled: true
      - name: exported
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: if-return
        disabled: true
      - name: max-control-nesting
        disabled: true
      - name: redefines-builtin-id
        disabled: true
      - name: package-comments
        disabled: true

  forbidigo:
    forbid:
      - pattern: 'fmt\.Errorf'
        msg: 'Please use errors.Wrap|Wrapf|Errorf instead'
      - pattern: 'ioutil\.ReadDir'
        msg: 'Please use os.ReadDir'

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx

    - path: cmd/
      text: "unused-parameter"

  exclude:
    - "declaration of 'err' shadows declaration at"

run:
  timeout: 5m
  go: "1.25"
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
