# DivineSense golangci-lint Configuration
# https://golangci-lint.run/usage/configuration/
# Version: v1.64+

# ===========================================================================
# Run Configuration
# ===========================================================================
run:
  # Go version to use
  go: "1.25"

  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Module download mode
  modules-download-mode: readonly

  # Enable caching for faster runs
  cache: true

  # Number of CPUs to use (0 = auto)
  concurrency: 4

# ===========================================================================
# Linters Configuration
# ===========================================================================
linters:
  # ================================================================
  # Core Linters (Must Have)
  # ================================================================
  enable:
    # Code formatting
    - gofmt           # Standard gofmt

    # Static analysis
    - govet           # Standard go vet
    - staticcheck     # Advanced static analysis
    - gosimple        # Simplification suggestions
    - unused          # Detect unused code

    # Error handling
    - errcheck        # Check unchecked errors
    - errorlint       # Error wrapping issues

    # Type checking
    - typecheck       # Standard type checker

    # Code quality
    - ineffassign     # Detect ineffectual assignments
    - prealloc        # Detect slice pre-allocation opportunities

  # ================================================================
  # Security & Bug Detection
  # ================================================================
    - gosec           # Security issues
    - bodyclose       # HTTP response body close
    - sqlclosecheck   # SQL rows close
    - rowserrcheck    # SQL rows.Err check

  # ================================================================
  # Code Style & Quality (Optional but Recommended)
  # ================================================================
    - gocritic        # Code style suggestions
    - misspell        # Spelling mistakes
    - unconvert       # Remove unnecessary type conversions
    - nilerr          # Check for nil errors

  # ================================================================
  # Disabled Linters (Too Noisy / Not Needed)
  # ================================================================
  disable:
    - exhaustive      # Enum exhaustiveness (too noisy)
    - funlen          # Function length (use code review instead)
    - lll             # Line length (use code review instead)
    - gocyclo         # Cyclomatic complexity (use code review instead)
    - varnamelen      # Variable name length (too opinionated)
    - wsl             # Whitespace linter (too strict)
    - err113          # Dynamic error checks (too strict)
    - nestif          # Nested if depth (use code review instead)
    - noctx           # Missing context (too many false positives)

# ===========================================================================
# Linters Settings
# ===========================================================================
linters-settings:
  # ================================================================
  # govet - Standard Go Vet
  # ================================================================
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - shadow  # Shadowed variables (too many false positives)

  # ================================================================
  # errcheck - Check Unchecked Errors
  # ================================================================
  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check blank identifier (_)
    check-blank: true

  # ================================================================
  # gosec - Security Linter
  # ================================================================
  gosec:
    # Exclude specific checks
    excludes:
      - G104  # Errors not checked (errcheck handles this)
      - G307  # Deferring file close (bodyclose handles this)

  # ================================================================
  # gocritic - Code Style Suggestions
  # ================================================================
  gocritic:
    # Enable only specific tags (disable experimental to reduce noise)
    enabled-tags:
      - diagnostic
      - performance
      - style

  # ================================================================
  # prealloc - Slice Pre-allocation
  # ================================================================
  prealloc:
    simple: true       # Simple loops
    range-loops: true  # Range loops
    for-loops: false   # For loops (false positive prone)

  # ================================================================
  # misspell - Spelling Checker
  # ================================================================
  misspell:
    locale: US

  # ================================================================
  # forbidigo - Forbid Specific Code Patterns
  # ================================================================
  forbidigo:
    forbid:
      # Use errors.Wrap instead of fmt.Errorf
      - pattern: 'fmt\.Errorf'
        msg: 'Please use errors.Wrap|Wrapf|Errorf instead'
      # Use os.ReadDir instead of ioutil.ReadDir
      - pattern: 'ioutil\.ReadDir'
        msg: 'Please use os.ReadDir (deprecated since Go 1.16)'

# ===========================================================================
# Issues Configuration
# ===========================================================================
issues:
  # Show all issues (don't use default excludes)
  exclude-use-default: false

  # Maximum issues per linter (0 = unlimited)
  max-issues-per-linter: 0
  max-same-issues: 0

  # ================================================================
  # Exclude Directories (Generated code, vendor, etc.)
  # ================================================================
  exclude-dirs:
    - build
    - dist
    - vendor
    - third_party
    - testdata
    - examples
    - Godeps
    - builtin
    - proto/gen

  # ================================================================
  # Exclude File Patterns
  # ================================================================
  exclude-files:
    - ".*\\.gen\\.go$"
    - ".*\\.gen\\.yaml$"
    - ".*\\.mock\\.go$"
    - ".*_string\\.go$"

  # ================================================================
  # Exclude Rules (Path-Specific)
  # ================================================================
  exclude-rules:
    # Test files: relax error checking
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - bodyclose
        - sqlclosecheck

    # Main packages: unused params are OK (for CLI entry points)
    - path: cmd/
      linters:
        - unused
      text: "unused-parameter"

    # Plugin code: allow specific patterns
    - path: plugin/
      text: "ST1005"  # staticcheck: error strings (plugin code has custom errors)

    # Mock files: skip style checks
    - path: .mock\.go$
      linters:
        - gocritic
        - misspell
        - errcheck
        - prealloc

    # AI agent callbacks: callback errors are intentionally not checked
    - path: plugin/ai/agent/
      linters:
        - errcheck
      text: "Error return value.*not checked"

    # AI agent callbacks: callback errors are intentionally not checked
    - path: plugin/ai/agent/
      linters:
        - errorlint
      text: "comparing with != will fail on wrapped errors"

  # ================================================================
  # Exclude Specific Issues
  # ================================================================
  exclude:
    # Shadowed variable warnings (often false positives)
    - "declaration of 'err' shadows declaration at"

    # SA1019: deprecated usage (we can't fix external deps)
    - "SA1019:"

    # Context-related warnings that are often false positives
    - "should pass context as first argument"

    # "cancelled" is valid English (UK) spelling, accepted alongside "canceled"
    - "`cancelled` is a misspelling of `canceled`"

    # gocritic suggestions that are too opinionated
    - "emptyStringTest:.*"
    - "builtinShadow:.*"
    - "builtinShadowDecl:.*"
    - "paramTypeCombine:.*"
    - "appendCombine:.*"
    - "sprintfQuotedString:.*"
    - "ifElseChain:.*"
    - "unnamedResult:.*"
    - "commentedOutCode:.*"
    - "elseif:.*"
    - "octalLiteral:.*"
    - "hugeParam:.*"
    - "regexpSimplify:.*"
    - "rangeValCopy:.*"
    - "assignOp:.*"
    - "typeAssertChain:.*"
    - "nestingReduce:.*"
    - "unnecessaryDefer:.*"

    # gosec issues that are acceptable in this context
    - "G301:.*"  # Directory permissions (intentional)
    - "G307:.*"  # Deferring file close (handled by bodyclose)
    - "G204:.*"  # Subprocess with tainted input (user input is validated elsewhere)
    - "G115:.*"  # Integer overflow conversion (handled by business logic)
    - "G107:.*"  # HTTP request with variable url (validated elsewhere)
    - "G304:.*"  # File inclusion via variable (validated elsewhere)
    - "G306:.*"  # WriteFile permissions (intentional for temp files)
    - "G109:.*"  # Potential Integer overflow (handled by business logic)
    - "G201:.*"  # SQL string formatting (WHERE clause is sanitized)
    - "G202:.*"  # SQL string concatenation (parameters are sanitized)

    # fieldalignment - minor optimization, not blocking
    - "fieldalignment:.*"

    # ineffassign - often false positives in complex code
    - "ineffectual assignment to.*"

    # "dialogues" is valid English (international spelling)
    - "`dialogues` is a misspelling of `dialogs`"

    # prealloc - optimization suggestion, not blocking
    - "Consider pre-allocating.*"

    # staticcheck - unused value in mock/test code
    - "this value of .* is never used"

    # SA4006 - unused value in complex code
    - "SA4006:.*"

    # errcheck - patterns where error checking is intentionally omitted
    - "Error return value of .* is not checked"
    - "Error return value is not checked"
    - "Error return value of .* not checked"

    # nilerr - often false positives in valid error handling patterns
    - "error is not nil .* but it returns nil"

    # unconvert - unnecessary conversion (minor issue)
    - "unnecessary conversion"

    # errorlint - type assertions on error are acceptable in this codebase
    - "type assertion on error will fail on wrapped errors"
    - "comparing with != will fail on wrapped errors"

    # unused - test fields
    - "field .* is unused"

    # gocritic - whyNoLint
    - "whyNoLint:.*"

  # Uniq by line (deduplicate issues on same line)
  uniq-by-line: true

# ===========================================================================
# Output Configuration
# ===========================================================================
output:
  # Output format
  formats:
    - format: colored-line-number
  # Print issues lines
  print-issued-lines: true
  # Print linter name
  print-linter-name: true
  # Sort results
  sort-results: true
