name: Bug Report / Bug 报告
description: Create a report to help us improve / 用于提交错误报告，帮助我们改进
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢您反馈 Bug！请填写以下表单以帮助我们定位和解决问题。
        Thank you for reporting a bug! Please complete the form below.

  - type: checkboxes
    id: pre-check
    attributes:
      label: 提交前检查 / Pre-submission Checklist
      description: 请确认您已完成以下步骤 / Please confirm you have completed the following steps
      options:
        - label: 我已搜索现有的 Issue，确认该 Bug 未被报告过 / I have searched existing issues
          required: true
        - label: 我已在最新版本中测试了该问题 / I have tested on the latest version
          required: true

  - type: dropdown
    id: issue-location
    attributes:
      label: 问题发生位置 / Issue Location
      description: 选择您是在哪里遇到的问题 / Where did you encounter this bug?
      options:
        - 最新稳定版 (Latest Stable)
        - 最新开发版 (Latest Dev / Nightly)
        - 旧版本 (Older Version)
      default: 0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 版本号 / Version
      description: 提供具体的版本号 (例如 v0.1.0) / Provide the exact version (e.g., v0.1.0)
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述 / Bug Description
      description: 清晰简洁地描述 Bug 是什么 / A clear and concise description of the bug
      placeholder: 当我尝试...时，应用发生了... / When I try to..., the app...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 复现步骤 / Steps to Reproduce
      description: 详细的复现步骤 / Detailed steps to reproduce
      placeholder: |
        1. 进入页面 '...'
        2. 点击 '...'
        3. 参见错误...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为 / Expected Behavior
      description: 您预期应该发生什么？ / What did you expect to happen?
      placeholder: 我预期... / I expected...

  - type: textarea
    id: additional-context
    attributes:
      label: 截图或补充信息 / Additional Context
      description: 添加截图、浏览器/系统信息、部署方式等 / Add screenshots, browser/OS info, deployment method
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
        - Deployment: Docker
        - Database: SQLite
